// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEBO5JpG_x6OScMytBHuUHE8yZB5cj8Hs',
    appId: '1:646468017816:web:1836e720623a5561a0baed',
    messagingSenderId: '646468017816',
    projectId: 'asistenciaceneris-app',
    authDomain: 'asistenciaceneris-app.firebaseapp.com',
    storageBucket: 'asistenciaceneris-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKs83Gl3FF3OKu1EWrMOIyamhUSfyuNs',
    appId: '1:646468017816:android:b47c8202e226e127a0baed',
    messagingSenderId: '646468017816',
    projectId: 'asistenciaceneris-app',
    storageBucket: 'asistenciaceneris-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjvuQKJqSums3NnsoQ87a7g1dI0ciRxE',
    appId: '1:646468017816:ios:f4d0bcb212883c05a0baed',
    messagingSenderId: '646468017816',
    projectId: 'asistenciaceneris-app',
    storageBucket: 'asistenciaceneris-app.firebasestorage.app',
    iosBundleId: 'com.example.assistenciacenerisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjvuQKJqSums3NnsoQ87a7g1dI0ciRxE',
    appId: '1:646468017816:ios:f4d0bcb212883c05a0baed',
    messagingSenderId: '646468017816',
    projectId: 'asistenciaceneris-app',
    storageBucket: 'asistenciaceneris-app.firebasestorage.app',
    iosBundleId: 'com.example.assistenciacenerisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEBO5JpG_x6OScMytBHuUHE8yZB5cj8Hs',
    appId: '1:646468017816:web:5338ba61fec97311a0baed',
    messagingSenderId: '646468017816',
    projectId: 'asistenciaceneris-app',
    authDomain: 'asistenciaceneris-app.firebaseapp.com',
    storageBucket: 'asistenciaceneris-app.firebasestorage.app',
  );
}
